---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: studylife-webhooks-secrets
  namespace: studylife-webhooks
spec:
  encryptedData:
    STUDYLIFE_WEBHOOKS_SHARED_SECRET: AgAnfRjgk6ssq8CYfRHnMDAuumTVuT1kwRYMtwKhA8ELhyCOW/XbtcuzRXdLxmT5W6TMwWRFX5v8ac0IpNupzqJOPlJz3tp1DTwJ8SQgchqlOHp322V1GFsydPrIHRBnzqdYLPmDwnCoPNuGZEuJ2NgUh4sWZ4d7rVqm1viraWLYl9s6FU0Bay6Gn0yjN9am1UhFNjR2zGC4P9kz4omc9oyuZWqCr8h3jDTUs8FJbAz4pz+T220DUIdVcYz6DL8H0mPBMNLtrJ27pnyPVF5Hf1CxlpSiRDJgtnMLWm5WjTljZSt8p+OV0KSE2FpDqvrkzEVQ0Mc2rX1T998OZHSNqwvZKuD/H6Ou/KCcdSOvujM6st9OXm+BUIjbigP3yQFyXW+9vDHAZ3x1lviMZalwb98iZRRXAlQgl4q/B322YOTe2c5gfvdyTvbJkyUJnw6HL7QNM0mtKdEKgBqHFYshfmDj25zvbwNBVEs4ySP4YIbrL1giXspuKoAIC+2sbdHJXEjO1FIwNRSsJCYBQNyMg2ogJb6Rw88wCa3BbKtk0qhQ3vkC3ZdUXepLupEw6s9x7l/k+42xt2CySTq4Wu8QpNZ2GB86k4dzUDU0J96a527sWBWoOC3xP1WJg0nlIlGLRYDc/AfvXrRURsNn55O4eloDzsB7DiPFnZRqu0ziZCQ/lt78HjyxRkNEQZ3QIViEp+A+tXMdWr1Ee+DnVBCSPiRP9cXBz8GfUgNWKThYYpgweMlxJcpZyHqlyGAhPw==
  template:
    metadata:
      name: studylife-webhooks-secrets
      namespace: studylife-webhooks
    type: Opaque
